// flow-typed signature: a8b479ec1e46695c447cec9267ae3ccd
// flow-typed version: <<STUB>>/dev-null-stream_v0.0.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dev-null-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dev-null-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dev-null-stream/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dev-null-stream/index' {
  declare module.exports: $Exports<'dev-null-stream'>;
}
declare module 'dev-null-stream/index.js' {
  declare module.exports: $Exports<'dev-null-stream'>;
}
declare module 'dev-null-stream/test/test.js' {
  declare module.exports: $Exports<'dev-null-stream/test/test'>;
}
