// flow-typed signature: 6b9750d9f952d8a72fe29aac2682de69
// flow-typed version: <<STUB>>/minimalcss_v0.7.6/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minimalcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minimalcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minimalcss/bin/e2e' {
  declare module.exports: any;
}

declare module 'minimalcss/bin/minimalcss' {
  declare module.exports: any;
}

declare module 'minimalcss/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'minimalcss/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'minimalcss/dummy' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.anchors' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.ast' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.facebook' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.gotos' {
  declare module.exports: any;
}

declare module 'minimalcss/hack' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.multipleurls' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.multipleurls.sync' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.nomincss' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.run.error' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.run' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.run.minify' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.run.utils' {
  declare module.exports: any;
}

declare module 'minimalcss/hack.with-browser' {
  declare module.exports: any;
}

declare module 'minimalcss/src/run' {
  declare module.exports: any;
}

declare module 'minimalcss/src/utils' {
  declare module.exports: any;
}

declare module 'minimalcss/tests/main.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minimalcss/bin/e2e.js' {
  declare module.exports: $Exports<'minimalcss/bin/e2e'>;
}
declare module 'minimalcss/bin/minimalcss.js' {
  declare module.exports: $Exports<'minimalcss/bin/minimalcss'>;
}
declare module 'minimalcss/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'minimalcss/coverage/lcov-report/prettify'>;
}
declare module 'minimalcss/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'minimalcss/coverage/lcov-report/sorter'>;
}
declare module 'minimalcss/dummy.js' {
  declare module.exports: $Exports<'minimalcss/dummy'>;
}
declare module 'minimalcss/hack.anchors.js' {
  declare module.exports: $Exports<'minimalcss/hack.anchors'>;
}
declare module 'minimalcss/hack.ast.js' {
  declare module.exports: $Exports<'minimalcss/hack.ast'>;
}
declare module 'minimalcss/hack.facebook.js' {
  declare module.exports: $Exports<'minimalcss/hack.facebook'>;
}
declare module 'minimalcss/hack.gotos.js' {
  declare module.exports: $Exports<'minimalcss/hack.gotos'>;
}
declare module 'minimalcss/hack.js' {
  declare module.exports: $Exports<'minimalcss/hack'>;
}
declare module 'minimalcss/hack.multipleurls.js' {
  declare module.exports: $Exports<'minimalcss/hack.multipleurls'>;
}
declare module 'minimalcss/hack.multipleurls.sync.js' {
  declare module.exports: $Exports<'minimalcss/hack.multipleurls.sync'>;
}
declare module 'minimalcss/hack.nomincss.js' {
  declare module.exports: $Exports<'minimalcss/hack.nomincss'>;
}
declare module 'minimalcss/hack.run.error.js' {
  declare module.exports: $Exports<'minimalcss/hack.run.error'>;
}
declare module 'minimalcss/hack.run.js' {
  declare module.exports: $Exports<'minimalcss/hack.run'>;
}
declare module 'minimalcss/hack.run.minify.js' {
  declare module.exports: $Exports<'minimalcss/hack.run.minify'>;
}
declare module 'minimalcss/hack.run.utils.js' {
  declare module.exports: $Exports<'minimalcss/hack.run.utils'>;
}
declare module 'minimalcss/hack.with-browser.js' {
  declare module.exports: $Exports<'minimalcss/hack.with-browser'>;
}
declare module 'minimalcss/index' {
  declare module.exports: $Exports<'minimalcss'>;
}
declare module 'minimalcss/index.js' {
  declare module.exports: $Exports<'minimalcss'>;
}
declare module 'minimalcss/src/run.js' {
  declare module.exports: $Exports<'minimalcss/src/run'>;
}
declare module 'minimalcss/src/utils.js' {
  declare module.exports: $Exports<'minimalcss/src/utils'>;
}
declare module 'minimalcss/tests/main.test.js' {
  declare module.exports: $Exports<'minimalcss/tests/main.test'>;
}
