// flow-typed signature: fd53a34a521d965f80832922212a25aa
// flow-typed version: <<STUB>>/sourcemapped-stacktrace-node_v2.1.8/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sourcemapped-stacktrace-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sourcemapped-stacktrace-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sourcemapped-stacktrace-node/src/createBrowseResolver' {
  declare module.exports: any;
}

declare module 'sourcemapped-stacktrace-node/src/createNodeResolver' {
  declare module.exports: any;
}

declare module 'sourcemapped-stacktrace-node/src/createResolver' {
  declare module.exports: any;
}

declare module 'sourcemapped-stacktrace-node/src/falseFetcher' {
  declare module.exports: any;
}

declare module 'sourcemapped-stacktrace-node/src/fsFetcher' {
  declare module.exports: any;
}

declare module 'sourcemapped-stacktrace-node/src/indexBrowser' {
  declare module.exports: any;
}

declare module 'sourcemapped-stacktrace-node/src/indexNode' {
  declare module.exports: any;
}

declare module 'sourcemapped-stacktrace-node/src/mapStackTrace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sourcemapped-stacktrace-node/src/createBrowseResolver.js' {
  declare module.exports: $Exports<'sourcemapped-stacktrace-node/src/createBrowseResolver'>;
}
declare module 'sourcemapped-stacktrace-node/src/createNodeResolver.js' {
  declare module.exports: $Exports<'sourcemapped-stacktrace-node/src/createNodeResolver'>;
}
declare module 'sourcemapped-stacktrace-node/src/createResolver.js' {
  declare module.exports: $Exports<'sourcemapped-stacktrace-node/src/createResolver'>;
}
declare module 'sourcemapped-stacktrace-node/src/falseFetcher.js' {
  declare module.exports: $Exports<'sourcemapped-stacktrace-node/src/falseFetcher'>;
}
declare module 'sourcemapped-stacktrace-node/src/fsFetcher.js' {
  declare module.exports: $Exports<'sourcemapped-stacktrace-node/src/fsFetcher'>;
}
declare module 'sourcemapped-stacktrace-node/src/indexBrowser.js' {
  declare module.exports: $Exports<'sourcemapped-stacktrace-node/src/indexBrowser'>;
}
declare module 'sourcemapped-stacktrace-node/src/indexNode.js' {
  declare module.exports: $Exports<'sourcemapped-stacktrace-node/src/indexNode'>;
}
declare module 'sourcemapped-stacktrace-node/src/mapStackTrace.js' {
  declare module.exports: $Exports<'sourcemapped-stacktrace-node/src/mapStackTrace'>;
}
